### ISSUE TITLE
iltorb issues - causing ci build  fail

### ISSUE THREAD

**Issue by Hotell** [erwinmombay/brotli-size#7]
build log:
https://travis-ci.org/Hotell/typescript-lib-starter/builds/477697808

node: 8.15
yarn 1.13

**error:**

```
Error: Cannot find module './build/bindings/iltorb.node'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/Hotell/typescript-lib-starter/node_modules/iltorb/index.js:10:40)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by Hotell** [comment]
hmm so it is because I install things via `--ignore-scripts` flag. Just curious if it can be fixed somehow

**Comment by erwinmombay** [comment]
@Hotell were you able to resolve the issue? sorry for the SUPER late reply to this

**Comment by kristoferbaxter** [comment]
@Hotell – If you update to the latest version this should be fixed. (Note: Requires Node 10.16+)

**Comment by kristoferbaxter** [comment]
Closing this issue, if the latest version continues to exhibit issues for you please reopen.
